// Code generated by goctl. DO NOT EDIT.
package types

type GenerateReq struct {
	Url string `json:"url"`
}

type GenerateRes struct {
	ShortUrl string `json:"short_url"`
}

type RedirectReq struct {
	ShortUrl string `json:"short_url""`
}

type RedirectRes struct {
}
