// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"github.com/nicolerobin/shorturl/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/generate",
				Handler: generateHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/:short_url",
				Handler: redirectHandler(serverCtx),
			},
		},
	)
}
